In [ ]:
from datetime import UTC, datetime, timedelta

import yfinance as yf

In [37]:
m7 = ["MSFT", "AAPL", "GOOGL", "AMZN", "NVDA", "META", "TSLA", "UKNOWN_TICKER"]
start = (
    datetime(year=2026, month=9, day=1, tzinfo=UTC).date() - timedelta(days=10)
).isoformat()
end = (datetime.now(tz=UTC).date() + timedelta(days=1)).isoformat()
data = yf.download(m7, start=start, end=end, auto_adjust=True)
closes = data.Close

[**********************75%***********            ]  6 of 8 completedHTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: UKNOWN_TICKER"}}}
$UKNOWN_TICKER: possibly delisted; no timezone found
[*********************100%***********************]  8 of 8 completed

1 Failed download:
['UKNOWN_TICKER']: possibly delisted; no timezone found

In [ ]:
data

Price          Adj Close       Close                                      \
Ticker     UKNOWN_TICKER        AAPL        AMZN       GOOGL        META
Date
2026-08-24           NaN  310.339996  262.070007  347.836426  558.579224
2026-08-25           NaN  309.899994  261.059998  346.737122  569.600464
2026-08-26           NaN  313.450012  260.279999  341.780304  575.685669
2026-08-27           NaN  314.579987  256.260010  340.431183  570.649597
2026-08-28           NaN  319.700012  266.429993  346.367371  577.564209
2026-08-31           NaN  316.850006  259.769989  339.132019  571.888672
2026-09-01           NaN  325.130005  254.919998  334.804779  578.083740
2026-09-02           NaN  324.959991  254.979996  336.903442  592.382446
2026-09-03           NaN  328.209991  258.899994  342.260010  610.198425
2026-09-04           NaN  319.970001  258.510010  338.459991  616.283630
2026-09-08           NaN  316.220001  256.970001  338.359985  612.996216
2026-09-09           NaN  315.339996  252.399994  330.649994  653.174500
2026-09-10           NaN  326.570007  251.889999  332.600006  643.871887
2026-09-11           NaN  332.269989  256.779999  338.500000  647.519043
2026-09-14           NaN  333.079987  253.539993  349.390015  665.075134
2026-09-15           NaN  331.339996  248.419998  344.980011  669.711487
2026-09-16           NaN  332.410004  245.960007  342.869995  672.779053
2026-09-17           NaN  337.000000  251.190002  347.329987  681.771973
2026-09-18           NaN  336.130005  253.710007  349.540009  665.225037
2026-09-21           NaN  338.980011  258.450012  354.970001  741.250000
2026-09-22           NaN  339.750000  254.979996  351.160004  736.599976
2026-09-23           NaN  337.019989  249.270004  337.829987  744.099976
2026-09-24           NaN  337.185608  249.630005  341.320007  776.659973

Price                                                               High  ...  \
Ticker            MSFT        NVDA        TSLA UKNOWN_TICKER        AAPL  ...
Date                                                                      ...
2026-08-24  487.309998  208.246979  348.950012           NaN  313.359985  ...
2026-08-25  491.709991  212.811874  350.250000           NaN  313.589996  ...
2026-08-26  496.369995  209.425659  345.820007           NaN  315.429993  ...
2026-08-27  505.059998  227.725174  354.809998           NaN  315.399994  ...
2026-08-28  513.530029  217.306839  348.750000           NaN  322.369995  ...
2026-08-31  507.290009  220.533234  367.950012           NaN  321.239990  ...
2026-09-01  501.019989  217.196976  356.089996           NaN  327.299988  ...
2026-09-02  496.820007  224.159180  357.010010           NaN  328.399994  ...
2026-09-03  510.119995  228.194656  376.369995           NaN  330.809998  ...
2026-09-04  499.700012  230.102524  354.079987           NaN  328.929993  ...
2026-09-08  493.950012  225.477692  368.160004           NaN  320.700012  ...
2026-09-09  491.649994  223.419998  367.809998           NaN  319.149994  ...
2026-09-10  492.440002  218.360001  363.559998           NaN  326.739990  ...
2026-09-11  495.630005  218.289993  365.440002           NaN  336.220001  ...
2026-09-14  505.410004  210.960007  358.970001           NaN  335.500000  ...
2026-09-15  497.119995  212.169998  356.579987           NaN  331.779999  ...
2026-09-16  490.299988  213.899994  358.079987           NaN  335.480011  ...
2026-09-17  497.750000  219.339996  366.200012           NaN  338.339996  ...
2026-09-18  493.779999  222.270004  364.269989           NaN  338.489990  ...
2026-09-21  501.609985  227.380005  375.299988           NaN  339.640015  ...
2026-09-22  498.000000  228.869995  378.899994           NaN  345.339996  ...
2026-09-23  500.589996  225.509995  380.119995           NaN  341.799988  ...
2026-09-24  497.195007  224.149902  379.070007           NaN  338.910004  ...

Price             Open                  Volume                                \
Ticker            TSLA UKNOWN_TICKER      AAPL      AMZN     GOOGL      META
Date
2026-08-24  361.410004           NaN  34673600  28070500  26338200  12990600
2026-08-25  349.579987           NaN  25869800  25550200  20649700   9769100
2026-08-26  345.269989           NaN  34024500  21528400  20420300  31416300
2026-08-27  346.160004           NaN  32419200  35927800  23391400  15221400
2026-08-28  357.100006           NaN  38649400  49547400  25347200  16042400
2026-08-31  347.209991           NaN  41242700  46089400  33493600  13383800
2026-09-01  360.899994           NaN  53167400  31700100  23342700  15796900
2026-09-02  360.410004           NaN  33776400  24013300  22582300  16552700
2026-09-03  365.820007           NaN  37225800  26891500  20726900  19737100
2026-09-04  362.070007           NaN  39606900  30749900  23189300  15966200
2026-09-08  357.100006           NaN  35477100  29398000  22915800  18909700
2026-09-09  368.250000           NaN  65640000  33055500  33151600  35900700
2026-09-10  360.600006           NaN  70011900  25484800  23557600  21531900
2026-09-11  364.200012           NaN  50716900  26724100  24708300  16925000
2026-09-14  359.779999           NaN  39269100  34352800  35905400  19332300
2026-09-15  358.750000           NaN  31748200  36275400  21928600  19502800
2026-09-16  357.929993           NaN  35981000  33488500  18928900  17217800
2026-09-17  367.480011           NaN  36700200  30438800  19238400  15928000
2026-09-18  369.000000           NaN  86588200  52274700  47631800  27596400
2026-09-21  371.640015           NaN  34999200  42979400  30455400  48720500
2026-09-22  379.070007           NaN  40711800  41982600  29788600  28122100
2026-09-23  380.100006           NaN  31587800  43999500  35463700  30346000
2026-09-24  377.350006           NaN  15440154  22958164  15832312  28265467

Price
Ticker          MSFT       NVDA      TSLA UKNOWN_TICKER
Date
2026-08-24  17230800  135187300  39190500           NaN
2026-08-25  19519000  122309000  29816700           NaN
2026-08-26  20758900  179900000  28573000           NaN
2026-08-27  28688800  298909800  30136200           NaN
2026-08-28  29207300  195116400  32972200           NaN
2026-08-31  27208900  124702700  61732300           NaN
2026-09-01  21046900  109756200  36193900           NaN
2026-09-02  15336100  157104700  33951900           NaN
2026-09-03  24125900  134681600  63601000           NaN
2026-09-04  18101800  135352400  65018200           NaN
2026-09-08  18882300  122965600  51078800           NaN
2026-09-09  12889600   82955500  32564300           NaN
2026-09-10  16038800  105768000  29667200           NaN
2026-09-11  14510500   89060100  30153000           NaN
2026-09-14  23091900  132267200  32477200           NaN
2026-09-15  17794600   88059700  30317700           NaN
2026-09-16  16670300   96563600  32177400           NaN
2026-09-17  17841600   94191300  38924100           NaN
2026-09-18  39622300  190287400  51922300           NaN
2026-09-21  27959900  109806100  36599600           NaN
2026-09-22  21652800   95746700  28229900           NaN
2026-09-23  19415500   89306700  33427400           NaN
2026-09-24  10635256   48929083  20783919           NaN

[23 rows x 41 columns]

In [38]:
closes.pct_change().head()

Ticker,AAPL,AMZN,GOOGL,META,MSFT,NVDA,TSLA,UKNOWN_TICKER
Date,,,,,,,,
2026-08-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-08-25,-0.001418,-0.003854,-0.003160,0.019731,0.009029,0.021921,0.003725,NaN
2026-08-26,0.011455,-0.002988,-0.014296,0.010683,0.009477,-0.015912,-0.012648,NaN
2026-08-27,0.003605,-0.015445,-0.003947,-0.008748,0.017507,0.087380,0.025996,NaN
2026-08-28,0.016276,0.039686,0.017437,0.012117,0.016770,-0.045750,-0.017080,NaN